---
name: "pre-release"

on:
  push:
    branches:
      - "native-builds"

jobs:
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2016, windows-latest ]

    steps:
      - uses: actions/checkout@v1
      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '19.3.0.2'
          java: 'java8'
      - run: java -version
      - name: Set up Visual C Build Tools Workload for Visual Studio 2017 Build Tools
        run: |
          choco install visualstudio2017-workload-vctools
          choco install -d windows-sdk-7.1 kb2519277
      - name: set env variables and run the Gradle build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          ./gradlew nativeImage
      - name: Rename the artifact to OS-unique name
        shell: bash
        run: |
          value=`cp build/graal/checksum build/graal/checksum-${{ matrix.os }}`
      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: checksum-${{ matrix.os }}.exe
          path: build/graal
#  pre-release:
#    name: "Pre Release"
#
#    runs-on: ${{ matrix.os }}
#    strategy:
#        matrix:
#          os: [ macos-latest, ubuntu-latest, windows-2016 ]
#
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Cache Gradle packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.gradle/caches
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
#          restore-keys: ${{ runner.os }}-gradle
#      - uses: DeLaGuardo/setup-graalvm@4.0
#        if: ${{ matrix.os == 'windows-2016' }}
#        with:
#          graalvm: '19.3.0.2'
#          java: 'java8'
#      - run: java -version
#      - name: Set up Visual C Build Tools Workload for Visual Studio 2017 Build Tools
#        if: ${{ matrix.os == 'windows-2016' }}
#        run: |
#          choco install visualstudio2017-workload-vctools
#      - name: "Build Native Image (Windows)"
#        if: ${{ matrix.os == 'windows-2016' }}
#        shell: cmd
#        run: |
#          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
#          gradlew.bat clean nativeImage
#      - name: "Build Native Image"
#        if: ${{ matrix.os != 'windows-2016' }}
#        run: |
#          ./gradlew clean nativeImage
#      - uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          automatic_release_tag: "latest"
#          prerelease: false
#          title: "Development Build"
#          files: |
#            build/graal/*
#            build/libs/*.jar
