---
name: "pre-release"

on:
  push:
    branches:
      - "native-builds"

jobs:
  pre-release:
    name: "Pre Release"

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ macos-latest, ubuntu-latest, windows-2016 ]


    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - uses: ilammy/msvc-dev-cmd@v1.5.0
        if: ${{ matrix.os == 'windows-2016' }}
      - uses: microsoft/setup-msbuild@v1
        if: ${{ matrix.os == 'windows-2016' }}
      - uses: ayltai/setup-graalvm@v1
        if: ${{ matrix.os == 'windows-2016' }}
        with:
          java-version: 8
          graalvm-version: 20.3.0
          native-image: true
      - name: "Build Native Image (Windows)"
        if: ${{ matrix.os == 'windows-2016' }}
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          gradlew.bat clean nativeImage
      - name: "Build Native Image"
        if: ${{ matrix.os != 'windows-2016' }}
        run: |
          ./gradlew clean nativeImage
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build/graal/*
            build/libs/*.jar
